### ISSUE TITLE
GOMAP version in GAF output

### ISSUE THREAD

**Issue by Thyra** [Dill-PICL/GOMAP-singularity#8]
In the final GAF output file, I feel it might be a good idea to include somewhat of a version in the assigned_by column, something like GOMAP-v1.2 . I know there is a date to each annotation but if we ever for example change PANNZER to PANNZER2 or just upgrade the databases/go.obo used by the tools the results on the same input would be different. And then it would be helpful if people can easily track back which version was used if they want to reproduce the results, or which annotation set is more current (and not just by the arbitrary creation date but actually by how current the tools are).

**Comment by wkpalan** [comment]
The idea is to add features to let users manually set values for the input config file. Any
GAF column can be customized by adding the additional config options, except a few that are needed by annotation tools. 

```
data:
    go:
        gaf_col_data:
            db: GOMAP
            db_reference: GOMAP:0000
            evidence_code: IEA
            db_object_type: gene
```

The assigned by column can be customized using the following config options
```
pipeline:
  version:          '1.1.0'
  name:             GOMAP
```
this will produce GOMAP-1.1.0 as the assigned by column
